name: digable_task
description: Dig Dig Task!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  drift: ^2.5.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.12
  riverpod_annotation: ^1.1.1
  sqlite3_flutter_libs: ^0.5.12
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2
  pedantic_mono: ^1.21.1
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true

  fonts:
    - family: MPLUS1
      fonts:
        - asset: assets/fonts/Mplus1-Regular.ttf

  assets:
    - assets/icons/      

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_128.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_128.png"
